apiVersion: v1
kind: Service
metadata:
  name: validator-service
  labels:
    environment: default
spec:
  type: LoadBalancer
  ports:
  - port: 8545
    targetPort: 8545
    protocol: TCP
    name: rpc
  - port: 8546
    targetPort: 8546
    protocol: TCP
    name: ws
  selector:
    role: validator
