apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    environment: {{ template "environment" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.staticIP }}
  clusterIP: {{ .Values.service.staticIP | quote }}
  {{- end }}
  ports:
  - port: {{ .Values.ethereum.port }}
    targetPort: {{ .Values.ethereum.port }}
    protocol: TCP
    name: p2p
  selector:
    app: {{ template "fullname" . }}
