apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}-secret"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    environment: {{ template "environment" . }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.volumes.keystore.azureStorageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.volumes.keystore.azureStorageAccountKey | b64enc }}